### ISSUE TITLE
Getting an error straight from the beginning

### ISSUE THREAD

**Issue by smileart** [aaaton/golem#15] opened 2020-04-02 20:14 UTC
## How to reproduce

Import library and dictionary as in example code from README.md

## Experienced Issue

````bash
../../../go/pkg/mod/github.com/aaaton/golem@v0.0.0-20191129093449-a9f1a1b6b185/dicts/en/data.go:1:1: expected 'package', found version
````

## Expected Behaviour

Perhaps I'm doing something wrong, but that what happens when I just try to work with the lib as it done in example code. 🤷‍♂️

**Comment by aaaton** [comment] 2020-04-03 06:23
Thanks for the report. This is a duplicate of #13 and should be related to git lfs.

**Comment by smileart** [comment] 2020-04-03 09:10
@aaaton, sorry for duplicating that, yesterday GitHub experienced some issues I can swear I haven't seen that issue in the list. Thank you.

**Closed as completed** 2020-04-03 09:19 UTC

**Comment by aaaton** [comment] 2020-04-05 09:37
No worries. It wasn't there. I reopened it when you had the same problem
